### ISSUE TITLE
Offsetting columns does not work

### ISSUE THREAD

**Issue by JeroenVdb** [depersgroep/fannypack#16]
Offsetting cols doesn't work like described in the documentation.

Docs say we should use: col--offset-2
Code says: col--grid-offset-2

Example: https://codepen.io/JeroenVdb/pen/qpPvdN

**Comment by JeroenVdb** [comment]
I think we should change the code because I like the naming "col--offset-2" over "col--grid-offset-2".

**Comment by bengie** [comment]
nicely spot. Sloppy docs are my mistake

I prefer .col--grid-offset-x
