### ISSUE TITLE
Remove the normalize.css from the main stylesheet

### ISSUE THREAD

**Issue by FreDeRoover** [depersgroep/fannypack#7]
I personally don't think that adding the normalize.css to fannypack.css is a correct way of thinking.
Not all applications need the bloated normalize.css to have a browser reset.
A separate reset stylesheet should beter suit the needs of Fannypack imho, you could always refer to normalize.css as a dependency.

**Comment by bengie** [comment]
@FreDeRoover : sorry, we don't agree. Fannypack is a framework, not a plugin. If it was a plugin your remark would be correct. All Fannypack modules are in a way dependant on the reset to get a consistent look. And for developers who are less experienced in front-end this would confuse them. Now they only have to include 1 file.

Which reset (reset, normalize, custom , ...) we use is another discussion. ;-)
